// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_do_an.Models.Model_TT;

#nullable disable

namespace web_do_an.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_do_an.Models.ChiTietLichTrinh", b =>
                {
                    b.Property<int>("MaDD")
                        .HasColumnType("int");

                    b.Property<int>("MaLT")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDD", "MaLT");

                    b.HasIndex("MaLT");

                    b.ToTable("ChiTietLichTrinhs");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietPhuongTien", b =>
                {
                    b.Property<int>("MaCTTour")
                        .HasColumnType("int");

                    b.Property<int>("MaPT")
                        .HasColumnType("int");

                    b.Property<int>("TongSL")
                        .HasColumnType("int");

                    b.HasKey("MaCTTour", "MaPT");

                    b.HasIndex("MaPT");

                    b.ToTable("ChiTietPhuongTiens");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietTour", b =>
                {
                    b.Property<int>("MaCTTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTTour"));

                    b.Property<int?>("DiemKhoiHanhMaDKH")
                        .HasColumnType("int");

                    b.Property<int>("MaDKH")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoChoDaDat")
                        .HasColumnType("int");

                    b.Property<int?>("TourMaTour")
                        .HasColumnType("int");

                    b.HasKey("MaCTTour");

                    b.HasIndex("DiemKhoiHanhMaDKH");

                    b.HasIndex("TourMaTour");

                    b.ToTable("ChiTietTours");
                });

            modelBuilder.Entity("web_do_an.Models.DanhGia", b =>
                {
                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SoSao")
                        .HasColumnType("real");

                    b.Property<DateTime>("ThoiGianDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.HasKey("MaTour", "MaTK");

                    b.HasIndex("MaTK");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("web_do_an.Models.DiemDen", b =>
                {
                    b.Property<int>("MaDD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDD"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDD");

                    b.ToTable("DiemDens");
                });

            modelBuilder.Entity("web_do_an.Models.DiemKhoiHanh", b =>
                {
                    b.Property<int>("MaDKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDKH"));

                    b.Property<string>("DC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDKH");

                    b.ToTable("DiemKhoiHanhs");
                });

            modelBuilder.Entity("web_do_an.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLT"));

                    b.Property<int?>("ChiTietTourMaCTTour")
                        .HasColumnType("int");

                    b.Property<string>("HoatDongChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatDongSang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatDongTrua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCTTour")
                        .HasColumnType("int");

                    b.Property<string>("TeHoatDongToi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLT");

                    b.HasIndex("ChiTietTourMaCTTour");

                    b.ToTable("LichTrinhs");
                });

            modelBuilder.Entity("web_do_an.Models.LoaiTour", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiTours");
                });

            modelBuilder.Entity("web_do_an.Models.PhieuDatTour", b =>
                {
                    b.Property<int>("MaPDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPDT"));

                    b.Property<int?>("ChiTietTourMaCTTour")
                        .HasColumnType("int");

                    b.Property<string>("DichVuTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCTTour")
                        .HasColumnType("int");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanMaTK")
                        .HasColumnType("int");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<bool?>("TrangThaiPDT")
                        .HasColumnType("bit");

                    b.HasKey("MaPDT");

                    b.HasIndex("ChiTietTourMaCTTour");

                    b.HasIndex("TaiKhoanMaTK");

                    b.ToTable("PhieuDatTours");
                });

            modelBuilder.Entity("web_do_an.Models.PhuongTienDC", b =>
                {
                    b.Property<int>("MaPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPT"));

                    b.Property<int>("SoLuongCho")
                        .HasColumnType("int");

                    b.Property<string>("TenPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPT");

                    b.ToTable("PhuongTienDCs");
                });

            modelBuilder.Entity("web_do_an.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("DC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTourDaDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThaiTK")
                        .HasColumnType("bit");

                    b.HasKey("MaTK");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("web_do_an.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DichVuTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Gia")
                        .HasColumnType("real");

                    b.Property<int?>("LoaiTourMaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTaTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoDem")
                        .HasColumnType("int");

                    b.Property<int>("SoNgay")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiTour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTour");

                    b.HasIndex("LoaiTourMaLoai");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietLichTrinh", b =>
                {
                    b.HasOne("web_do_an.Models.DiemDen", "DiemDen")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaDD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_do_an.Models.LichTrinh", "LichTrinh")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaLT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiemDen");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietPhuongTien", b =>
                {
                    b.HasOne("web_do_an.Models.ChiTietTour", "ChiTietTour")
                        .WithMany("ChiTietPhuongTiens")
                        .HasForeignKey("MaCTTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_do_an.Models.PhuongTienDC", "PhuongTienDC")
                        .WithMany("ChiTietPhuongTiens")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietTour");

                    b.Navigation("PhuongTienDC");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietTour", b =>
                {
                    b.HasOne("web_do_an.Models.DiemKhoiHanh", "DiemKhoiHanh")
                        .WithMany()
                        .HasForeignKey("DiemKhoiHanhMaDKH");

                    b.HasOne("web_do_an.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourMaTour");

                    b.Navigation("DiemKhoiHanh");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("web_do_an.Models.DanhGia", b =>
                {
                    b.HasOne("web_do_an.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_do_an.Models.Tour", "Tour")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("web_do_an.Models.LichTrinh", b =>
                {
                    b.HasOne("web_do_an.Models.ChiTietTour", "ChiTietTour")
                        .WithMany()
                        .HasForeignKey("ChiTietTourMaCTTour");

                    b.Navigation("ChiTietTour");
                });

            modelBuilder.Entity("web_do_an.Models.PhieuDatTour", b =>
                {
                    b.HasOne("web_do_an.Models.ChiTietTour", "ChiTietTour")
                        .WithMany()
                        .HasForeignKey("ChiTietTourMaCTTour");

                    b.HasOne("web_do_an.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanMaTK");

                    b.Navigation("ChiTietTour");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("web_do_an.Models.Tour", b =>
                {
                    b.HasOne("web_do_an.Models.LoaiTour", "LoaiTour")
                        .WithMany()
                        .HasForeignKey("LoaiTourMaLoai");

                    b.Navigation("LoaiTour");
                });

            modelBuilder.Entity("web_do_an.Models.ChiTietTour", b =>
                {
                    b.Navigation("ChiTietPhuongTiens");
                });

            modelBuilder.Entity("web_do_an.Models.DiemDen", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");
                });

            modelBuilder.Entity("web_do_an.Models.LichTrinh", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");
                });

            modelBuilder.Entity("web_do_an.Models.PhuongTienDC", b =>
                {
                    b.Navigation("ChiTietPhuongTiens");
                });

            modelBuilder.Entity("web_do_an.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("web_do_an.Models.Tour", b =>
                {
                    b.Navigation("DanhGias");
                });
#pragma warning restore 612, 618
        }
    }
}
